# Generated by Django 3.2 on 2021-06-18 16:17

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0002_auto_20210617_1904'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='createquizmodel',
            name='correct_answers',
        ),
        migrations.RemoveField(
            model_name='createquizmodel',
            name='questions',
        ),
        migrations.CreateModel(
            name='SetQuizModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('correct_answers', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myApp.answermodel')),
                ('questions', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myApp.questionmodel')),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myApp.createquizmodel')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
