# Generated by Django 3.2.4 on 2021-06-28 13:49

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0005_auto_20210626_0540'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sharequizmodel',
            name='score',
        ),
        migrations.CreateModel(
            name='ScoreModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('score', models.IntegerField(default=0)),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myApp.createquizmodel')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myApp.usermodel')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
