# Generated by Django 3.2.4 on 2021-06-28 13:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0006_auto_20210628_1349'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ResultModel',
        ),
    ]
