# Generated by Django 3.2.4 on 2021-06-28 13:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0007_delete_resultmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='sharequizmodel',
            name='questions',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='myApp.questionmodel'),
            preserve_default=False,
        ),
    ]
